"""Initial Draft for ChatBulletServer.

Revision ID: 86516a2367af
Revises: None
Create Date: 2016-03-28 14:45:09.053349

"""

# revision identifiers, used by Alembic.
revision = '86516a2367af'
down_revision = None

from alembic import op
import sqlalchemy as sa
import ChatBulletServer._types


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('id', ChatBulletServer._types.UUIDType(length=16), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', ChatBulletServer._types.UUIDType(length=16), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('msg',
    sa.Column('id', ChatBulletServer._types.UUIDType(length=16), nullable=False),
    sa.Column('user_id', ChatBulletServer._types.UUIDType(length=16), nullable=False),
    sa.Column('room_id', ChatBulletServer._types.UUIDType(length=16), nullable=False),
    sa.Column('contents', sa.String(), nullable=False),
    sa.Column('sent', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_in_room',
    sa.Column('user_id', ChatBulletServer._types.UUIDType(length=16), nullable=True),
    sa.Column('room_id', ChatBulletServer._types.UUIDType(length=16), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_in_room')
    op.drop_table('msg')
    op.drop_table('user')
    op.drop_table('room')
    ### end Alembic commands ###
