"""Issue 11, is_restricted flag added.

Revision ID: 9f96f6469d60
Revises: 79f5c84b43cd
Create Date: 2016-03-29 15:27:01.689744

"""

# revision identifiers, used by Alembic.
revision = '9f96f6469d60'
down_revision = '79f5c84b43cd'

from alembic import op
import sqlalchemy as sa
import ChatBulletServer._types


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_restricted', sa.Boolean(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('is_restricted')

    ### end Alembic commands ###
